// Les réponses du sondage seront à renseigner ici.
// Pour chaque question, ajoute les 6 réponses les plus citées.
// "votes" = nombre de personnes ayant donné cette réponse.

const QUESTIONS = [
  {
    question: "Citez un plat français.",
    answers: [
{ text: "Bœuf bourguignon", votes: 27 },
{ text: "Raclette", votes: 12 },
{ text: "Tartiflette", votes: 9 },
{ text: "Choucroute", votes: 8 },
{ text: "Cassoulet", votes: 6 },
{ text: "Quiche lorraine", votes: 5 },

{ text: "Pot-au-feu", votes: 4 },
{ text: "Poulet frites", votes: 4 },

{ text: "Blanquette de veau", votes: 2 },
{ text: "Bouillabaisse", votes: 2 },
{ text: "Steak frites", votes: 2 },
{ text: "Ratatouille", votes: 2 },
{ text: "Lasagne", votes: 2 },

{ text: "Flammekueche", votes: 1 },
{ text: "Rougaille saucisse", votes: 1 },
{ text: "Côte de bœuf", votes: 1 },
{ text: "Croziflette", votes: 1 },
{ text: "Daube", votes: 1 },
{ text: "Bœuf carotte", votes: 1 },
{ text: "Fondue", votes: 1 },
{ text: "Moules-frites", votes: 1 },
{ text: "Galette-saucisse", votes: 1 },
{ text: "Boudin purée", votes: 1 }
]
  },
  {
    question: "Citez un prénom masculin commençant par M.",
    answers: [
{ text: "Maxime", votes: 22 },
{ text: "Mathieu / Matthieu", votes: 17 },
{ text: "Maurice", votes: 10 },
{ text: "Michel", votes: 8 },
{ text: "Mathis / Matisse", votes: 8 },
{ text: "Marcel", votes: 7 },
{ text: "Martin", votes: 5 },
{ text: "Marius", votes: 4 },
{ text: "Mathéo", votes: 2 },
{ text: "Malo", votes: 2 },
{ text: "Marc", votes: 2 },
{ text: "Maël", votes: 1 },
{ text: "Miguel", votes: 1 },
{ text: "Mario", votes: 1 },
{ text: "Matthias", votes: 1 },
{ text: "Maturin", votes: 1 },
{ text: "Maxence", votes: 1 },
{ text: "Melvin", votes: 1 },
{ text: "Mouloud", votes: 1 }
]
  },
  {
    question: "Citez un prénom féminin commençant par A.",
    answers: [
  { text: "Agathe", votes: 9 },
  { text: "Amélie", votes: 8 },
  { text: "Alice", votes: 7 },
  { text: "Adèle", votes: 6 },
  { text: "Aline", votes: 6 },
  { text: "Anna", votes: 6 },
  { text: "Alix", votes: 5 },
  { text: "Alexandra", votes: 4 },
  { text: "Anaïs", votes: 4 },
  { text: "Adeline", votes: 3 },
  { text: "Amandine", votes: 3 },
  { text: "Anne", votes: 3 },
  { text: "Aude", votes: 3 },
  { text: "Audrey", votes: 3 },
  { text: "Alexia", votes: 2 },
  { text: "Ambre", votes: 2 },
  { text: "Amélia", votes: 2 },
  { text: "Aurélie", votes: 2 },
  { text: "Adrien", votes: 1 },
  { text: "Alicia", votes: 1 },
  { text: "Alison", votes: 1 },
  { text: "Alizée", votes: 1 },
  { text: "Alma", votes: 1 },
  { text: "Amelle", votes: 1 },
  { text: "Anabelle", votes: 1 },
  { text: "Anal", votes: 1 },
  { text: "Anastasia", votes: 1 },
  { text: "Angeline", votes: 1 },
  { text: "Angélina", votes: 1 },
  { text: "Anita", votes: 1 },
  { text: "Annadele", votes: 1 },
  { text: "Annick", votes: 1 },
  { text: "Aurore", votes: 1 },
  { text: "Axelle", votes: 1 },
  { text: "Léa", votes: 1 }
]
  },
  {
    question: "Citez une excuse pour justifier un retard.",
    answers: [
  { text: "Panne de réveil", votes: 19 },
  { text: "Bouchons / embouteillages", votes: 19 },
  { text: "Transport en commun", votes: 8 },
  { text: "Travail / boulot", votes: 6 },
  { text: "Panne de voiture", votes: 6 },
  { text: "Tracteur sur la route", votes: 4 },
  { text: "Apéro", votes: 3 },
  { text: "Je n’ai pas vu l’heure", votes: 3 },
  { text: "Accident sur la route", votes: 2 },
  { text: "Chiottes", votes: 2 },
  { text: "Chien enfui", votes: 1 },
  { text: "Ménage", votes: 1 },
  { text: "Les enfants", votes: 1 },
  { text: "Le quart d’heure soudanais", votes: 1 },
  { text: "Rien à faire", votes: 1 },
  { text: "Pas envie de venir", votes: 1 },
  { text: "Rencontre imprévue", votes: 1 },
  { text: "Fatigue", votes: 1 },
  { text: "Gastro", votes: 1 },
  { text: "Travaux sur la route", votes: 1 },
  { text: "Ma femme", votes: 1 },
  { text: "Aqua poney", votes: 1 },
  { text: "Vêlage", votes: 1 },
  { text: "Foot", votes: 1 },
  { text: "Rendez-vous", votes: 1 },
  { text: "J’ai oublié", votes: 1 },
  { text: "Brushing", votes: 1 },
  { text: "Chaussures introuvables", votes: 1 },
  { text: "Déménagement", votes: 1 },
  { text: "Chèvres sur la route", votes: 1 },
  { text: "Que veux-tu que je te dise", votes: 1 },
  { text: "Renard était en panne", votes: 1 }
]

  },
  {
    question: "Quel objet essentiel emporteriez-vous sur une île déserte ?",
    answers: [
  { text: "Couteau", votes: 41 },
  { text: "Briquet", votes: 10 },
  { text: "Gourde / bouteille d’eau", votes: 6 },
  { text: "Livre", votes: 4 },
  { text: "Canne à pêche", votes: 4 },
  { text: "Brosse à dents", votes: 3 },
  { text: "Filtre à eau", votes: 2 },
  { text: "Oreiller", votes: 2 },
  { text: "Téléphone", votes: 2 },
  { text: "Tire-bouchon", votes: 2 },
  { text: "Tireuse à bière", votes: 2 },
  { text: "Maillot du Real", votes: 1 },
  { text: "Saucisson", votes: 1 },
  { text: "Bilboquet", votes: 1 },
  { text: "Moustiquaire", votes: 1 },
  { text: "Pierre à feu", votes: 1 },
  { text: "Lecteur de musique", votes: 1 },
  { text: "Boussole", votes: 1 },
  { text: "Maillot de bain", votes: 1 },
  { text: "Mon mari", votes: 1 },
  { text: "Antimoustique", votes: 1 },
  { text: "Allumettes", votes: 1 },
  { text: "Petit chien", votes: 1 },
  { text: "2 chevaux", votes: 1 },
  { text: "Parapluie", votes: 1 },
  { text: "Clé de 13", votes: 1 },
  { text: "Madeleine", votes: 1 }
]

  },
  {
    question: "Quel est le meilleur jour de la semaine ?",
    answers: [
  { text: "Samedi", votes: 37 },
  { text: "Vendredi", votes: 34 },
  { text: "Dimanche", votes: 13 },
  { text: "Jeudi", votes: 10 },
  { text: "Tous", votes: 1 }
]

  },
  {
    question: "Quelle est la première chose que vous faites en vous réveillant ?",
    answers: [
  { text: "Aller aux toilettes", votes: 28 },
  { text: "Regarder mon téléphone", votes: 16 },
  { text: "Éteindre / repousser le réveil", votes: 11 },
  { text: "Manger / déjeuner", votes: 8 },
  { text: "Boire (café, eau, jus de fruit)", votes: 7 },
  { text: "S’habiller", votes: 3 },
  { text: "Ouvrir les yeux", votes: 3 },
  { text: "Ouvrir les volets", votes: 3 },
  { text: "Se lever / descendre du lit", votes: 3 },
  { text: "Se rendormir", votes: 2 },
  { text: "Douche", votes: 2 },
  { text: "S’étirer", votes: 2 },
  { text: "Sortir Vaïa", votes: 1 },
  { text: "Vérifier mes bijoux de famille", votes: 1 },
  { text: "Rester au lit", votes: 1 },
  { text: "Bisou à ma partenaire", votes: 1 },
  { text: "Dire bonjour à son mari", votes: 1 },
  { text: "Regarder l’heure", votes: 1 },
  { text: "Gratitude", votes: 1 },
  { text: "Changer la couche de bébé", votes: 1 },
  { text: "Brosser les dents", votes: 1 }
]

  },
  {
    question: "Quel métier rêviez-vous de faire enfant ?",
    answers: [
  { text: "Agriculteur", votes: 14 },
  { text: "Maîtresse / Prof", votes: 14 },
  { text: "Footballeur", votes: 4 },
  { text: "Vétérinaire", votes: 4 },
  { text: "Coiffeur / Coiffeuse", votes: 4 },
  { text: "Conducteur d’engins", votes: 4 },
  { text: "Pilote automobile", votes: 3 },
  { text: "Infirmière", votes: 3 },
  { text: "Cuisinier", votes: 2 },
  { text: "Mécanicien", votes: 2 },
  { text: "Paysagiste", votes: 2 },
  { text: "Garde forestier", votes: 2 },
  { text: "Chanteuse", votes: 2 },
  { text: "Astronaute", votes: 2 },
  { text: "Styliste", votes: 1 },
  { text: "Actrice", votes: 1 },
  { text: "Décoratrice d’intérieur", votes: 1 },
  { text: "Architecte", votes: 1 },
  { text: "Éleveur", votes: 1 },
  { text: "Ébéniste", votes: 1 },
  { text: "Maçon", votes: 1 },
  { text: "Pâtissier", votes: 1 },
  { text: "Influenceur sur MYM", votes: 1 },
  { text: "Scientifique", votes: 1 },
  { text: "Éditrice de romans", votes: 1 },
  { text: "Paléontologue", votes: 1 },
  { text: "Soigneur animalier", votes: 1 },
  { text: "Vigneron", votes: 1 },
  { text: "Couturière", votes: 1 },
  { text: "Boxeur", votes: 1 },
  { text: "Sportif", votes: 1 },
  { text: "Boulanger", votes: 1 },
  { text: "Ambulancière", votes: 1 },
  { text: "Vulcanologue", votes: 1 },
  { text: "Vendeur de glace", votes: 1 },
  { text: "Préparatrice en pharmacie", votes: 1 },
  { text: "Diplomate", votes: 1 },
  { text: "Puéricultrice", votes: 1 },
  { text: "Pharmacienne", votes: 1 },
  { text: "Médecin", votes: 1 },
  { text: "Avocate", votes: 1 },
  { text: "Archéologue", votes: 1 },
  { text: "Pilote de chasse", votes: 1 },
  { text: "Militaire", votes: 1 }
]

  },
  {
    question: "Quel est votre parfum de glace préféré ?",
    answers: [
  { text: "Vanille", votes: 32 },
  { text: "Chocolat", votes: 9 },
  { text: "Citron", votes: 8 },
  { text: "Mangue", votes: 7 },
  { text: "Caramel / caramel beurre salé", votes: 7 },
  { text: "Pistache", votes: 5 },
  { text: "Framboise", votes: 3 },
  { text: "Fraise", votes: 3 },
  { text: "Menthe chocolat", votes: 3 },
  { text: "Cassis", votes: 2 },
  { text: "Fruit rouge", votes: 2 },
  { text: "Rhum raisin", votes: 2 },
  { text: "Café", votes: 1 },
  { text: "Melon", votes: 1 },
  { text: "Passion", votes: 1 },
  { text: "Pomme", votes: 1 },
  { text: "Turrón", votes: 1 },
  { text: "Noix de coco", votes: 1 },
  { text: "Citron meringué", votes: 1 },
  { text: "Cookies", votes: 1 },
  { text: "Noisette", votes: 1 },
  { text: "Rhubarbe", votes: 1 },
  { text: "Vanille fraise", votes: 1 },
  { text: "Chocolat pistache", votes: 1 }
]

  },
  {
    question: "Citez un gros mot que vous utilisez au volant.",
    answers: [
  { text: "Putain", votes: 29 },
  { text: "Connard / Connasse", votes: 25 },
  { text: "Enculé / Enculer", votes: 9 },
  { text: "Con / Conne", votes: 5 },
  { text: "Fils de pute", votes: 4 },
  { text: "Bon dieu / Nom de dieu", votes: 4 },
  { text: "Tocard", votes: 2 },
  { text: "Enfoiré", votes: 2 },
  { text: "Trou du cul", votes: 2 },
  { text: "Je ne conduis pas", votes: 2 },
  { text: "Aucun", votes: 2 },
  { text: "Blaireau", votes: 1 },
  { text: "Crétin", votes: 1 },
  { text: "Va te faire foutre", votes: 1 },
  { text: "Nik mok", votes: 1 },
  { text: "Avance Michel", votes: 1 },
  { text: "Sacré bobiaw", votes: 1 },
  { text: "Abruti", votes: 1 },
  { text: "Merde", votes: 1 },
  { text: "Sac à merde", votes: 1 }
]
  }
];

// Exemple de format :
// answers: [
//   { text: "Ratatouille", votes: 8 },
//   { text: "Bœuf bourguignon", votes: 6 },
//   { text: "Crêpes", votes: 5 },
//   { text: "Raclette", votes: 4 },
//   { text: "Quiche", votes: 3 },
//   { text: "Cassoulet", votes: 2 }
// ]
